apiVersion: apps/v1
kind: Deployment
metadata:
  name: viatab-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viatab-db
  template:
    metadata:
      labels:
        app: viatab-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: viatab
            - name: POSTGRES_USER
              value: viatab
            - name: POSTGRES_PASSWORD
              value: viatab
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          emptyDir: {}
